### ISSUE TITLE
aggressive settings modified

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#24]
To comment on reddit and watch a video on YouTube I had to change a few settings on the aggressive preset.  Just putting them out here for reference.   You may want a link in the add-on to come to the github page and a link to the wiki if you decide on using it :)

YouTube seemed to need all of these:
uncheck CSSOM View Module
uncheck File API
uncheck Fullscreen API
uncheck HTML: Web Storage
uncheck Media Source Extensions

uncheck Selection API (couldn't comment on reddit)

And I went ahead and checked these two because I don't need them:
check Service Workers
check Vibration API

**Comment by snyderp** [comment]
Thanks for these!  In the next version or two I'll make the ability to first import/export configuration  (issue #8), and then later to subscribe to configurations a la EasyList.  So hopefully that'll make it easier to maintain easy to get to tips like this.

In the meantime, I've moved this to a [wiki page](Web API Manager Tips and Suggestions), so hopefully others can find the info too.  If you have other suggested configurations, or would be interested in collaborating on building page lists, I'd be very interested in that

**Comment by snyderp** [comment]
I've also referenced the wiki page, and your suggestions, in the README file, so that others can find them.  Thanks again for your help!

**Comment by crssi** [comment]
Additionally those 3 breaks youtube:
```
DOM Parsing and Serialization
High Resolution Time Level 2
W3C DOM4
```

And the `W3C DOM4` is not alphabetically placed at the correct position on the "blocked standards" list.

And on facebook the following are breakage:
```
HTML: Channel Messaging
HTML: Web Storage
Selection API
```

I have never visit facebook so many times than now, testing functionality for WAM.

**Comment by snyderp** [comment]
@crssi thank you too!  Any chance I could ask you to add those to the Wiki? :)

**Comment by crssi** [comment]
Can I edit Wiki? And how?

**Comment by snyderp** [comment]
Yep!  If you're logged into GH you should be able to go [here](https://github.com/snyderp/web-api-manager/wiki), click edit in the top right corner, and edit away :)

I swear, this bananas situation should really only last for one or two more releases.  I hope to have import / export ready to go by Monday 🤞

**Comment by snyderp** [comment]
Oh, DERP… one more try? :)

**Comment by crssi** [comment]
Done ;)

Just for info:
I have now as "default" the aggressive with unchecked:
```
CSSOM View Module (yt)
DOM Parsing and Serialization (yt)
File API (yt)
Fullscreen API (general)
HTML: Channel Messaging (fb)
HTML: History Interface (ata)
HTML: Web Storage (fb,yt)
High Resolution Time Level 2 (yt)
Indexed Database API (general)
Media Source Extensions (yt)
Selection API (fb)
W3C DOM4 (yt)
```

And additionally checked:
```
Non-Standard
Performance Timeline
Screen Orientation API
Service Workers
Vibration API
WebVTT: The Web Video Text Tracks Format
```

Will follow the browsing experience with those now... until import/export is available.

Thank you
Cheers

**Comment by jawz101** [comment]
Screen orientation may be handy for Firefox on Android, no?
I didn't see the need to enable the other stuff you mentioned for yt (DOM Parsing and Serialization, W3C DOM4).  While errors were logged to the console my videos played fine full-screen and all.  Was anything necessarily broken when viewing YouTube with those disabled or were you just getting rid of error msgs in the console?

**Comment by jawz101** [comment]
I'm also wondering if an add-on has the ability to pull in content dynamically from a github page.  I always thought it'd be cool if there was a way to have descriptions of things pull from a github repo directly into an add-on.  That way anyone could clarify documentation of some button on the fly.

**Comment by crssi** [comment]
@jawz101 
I don't really care about errors in log, but those are helpful. I am focusing on breakage functionalities on the page.
Block `W3C DOM4` and all the content around will vanish.
Block `DOM Parsing and Serialization`, go to main youtube.com page. Click any video. The new page will not play, until you refresh. If you go directly to the video page, it will play OK.
There are sill other error in log, but I didn't find that those would break functionality.

Can you reproduce?

**Comment by jawz101** [comment]
Thanks.  Sorry, I'll play around on YouTube more today.  Again my first pass was based on a few minutes of clicking around on some popular sites to see if what I was looking for would work.  Probably didn't click around enough on YouTube to see if I would miss something.

My initial thing was to get a video to play.  It started playing but then it was only taking up a quarter of its player box, allowed another API and then that got fixed.  Then I couldn't switch to full screen until I allowed full screen api.

At that point I was doing what I needed so I stopped.

It'd be nice to find a way to incorporate our notes like this.  Personally, I'm most interested in disabling web code across the board instead of on a per site basis, so sane defaults sound like a nice topic for us.

I'm kinda curious how the aggressive settings were determined in the first place but I assume the add-on dev went with what is commonly dangerous or something.

**Comment by jawz101** [comment]
...plus, I'm just thinking of ways the add-on could take it a step further and show us how standards are used in the real world.  It'd be nice to know "75% of us disable xyz even though it's used by 5,000 websites.  Apparently it's used more for annoying content than actual content."  That way we could see what standards are pretty useless to the end user.

**Comment by jawz101** [comment]
... with the EFF leaving the w3c we really don't have a voice for privacy when it comes to web standards.  And since Google is a member of the consortium I assume they propose goofy standards often.

**Comment by snyderp** [comment]
@jawz101 @crssi 

This is interesting.  I like the idea of some anonymous analytics about whats blocked, what stays blocked, how many sites people view with what % of features blocked, etc.  That kind of data would be great, not only from a "how to improve the extension" perspective, but also from a research perspective, and maybe even pushing browser vendors to be more cautious in what they enable by default.

The collection part becomes a pickle though, especially since (I expect) this kind of extension will appeal to people with above average privacy and security needs / desires.  Spinning up Tor from the extension, and only collecting high level, aggregate statistics is one approach but would like to avoid adding the complexity of a Tor kind of thing at this point.

Do you know of how other folks in similar spots do things?

**Comment by jawz101** [comment]
No I don't.  The biggest thing I'd be concerned with is liability if it publicized a url for an intranet page or non-indexed site.

**Comment by snyderp** [comment]
I think this is a great idea, but realistically I'm not going to be able to get to it in the next week or three (my current priority here is on the subscriptions system).  But I created an issue to keep myself from forgetting it.  Thanks again!

**Comment by rEnr3n** [comment]
Youtube is not working for me based on the rules on wiki. I made some modifications on it. I use aggressive settings and unchecked the following. I also added some explanations for those who are meticulous. It might be overkill but..

1. `File API`
Checking this prevents the video from playing.
2. `Fullscreen API`
Checking this prevents exiting fullscreen using the keyboard shortcut or the icon at the bottom right. It can only be exited by pressing Esc.
3. `Media Source Extensions`
Checking this buffers the video but does not play it. It doesn't load comments too.
4. `High Resolution Time (Level 2)`
Checking this makes the video player always show the "play" button whether the video is playing or on pause.
5. `DOM Level 4`
Checking this causes general breakage. It breaks the sidebar. Logo is gone. Buttons at the top-right are gone. Main page does not scroll down. Only top three rows are displayed.
Related videos are gone. Like/Dislike (and adjacent) buttons are gone. Only two comments are loaded.
6. `Timing Control for Script-Based Animations`
Checking this causes general breakage. Sidebar does not load immediately. Buttons at the top-right are gone. Main page does not scoll down. Only top three rows are displayed.
It makes the video player always show the "pause" button whether the video is playing or on pause. Related videos does not load immediately. It only shows one item with no thumbnail. Like/Dislike buttons and description do not load immediately. Comments are not loaded.
7. `HTML: Channel Messaging`
Checking this makes searching on the main page non-functional when pressing enter. Clicking the search button will still work.
8. `CSS Object Model (CSSOM)`
Checking this makes the two buttons at the top-right (Youtube apps and Settings) not function. Seeking the video timeline using the mouse is inaccurate.

I did not include `CSSOM View Module` and `HTML: Web Storage` since they are unchecked in aggressive settings. I am not sure with `DOM Parsing and Serialization`. Checking it does not break anything for me. Can anyone check?

There is also one thing I cannot find the fix. Applying the settings above, searching does not rewrite the url accordingly. Clearing the settings will.

**Comment by snyderp** [comment]
@rEnr3n Ah, great, thank you for this!  Would you mind updating the wiki then?  You could even export the rule that you have working and add that JSON to the page, so others could import if they want to?

If you don't have a chance / or would prefer not to though, no worries, please just give me a heads up and I'll recreate myself.

About the URL, im not certain what the cause is on that.  I'll dig into it now.  Thanks!

**Comment by snyderp** [comment]
@rEnr3n Actually the issue here is that YouTube injects hidden iframes into the page for a variety of purposes (such as pre-fecthing more assets, or more to the case here, having a separate frame used to track your behavior on their page) (fwiw you can see these by loading the page and doing a `document.querySelectorAll("iframe")`)

Currently the extension prevents pages from directly accessing the contents of other frames / pages, to prevent sites from gaining access to blocked functionality, but pulling it out of the other frames.  The main problem is when a iframe is injected into a page, the steps that happen are

1. Iframe element is inserted into containing document
2. the DOM of the document in the iframe is build, but page content has been loaded and no script has been run
3. web extensions run and do whatever they way
4. Execution of the frames content continues as expected.

However, clever pages can get around Web API Manager's protections (ie keeping pages from accessing parts of the Web API), by inserting an iframe, and the extracting references to blocked functionality between steps 2 and 3.

There are no good solutions to this (that I have been able to come up with so far, though Im still brainstorming), so what the extension does now is prevent documents from reaching the content of the child frames (though they can still use postmessage to communicate).  Preventing the parent page from access the contents of the child frame solves the security problem (the Web API security box holds), but it breaks pages that expect to be able to reach across frames in this way.

All that is a TL;DR way of saying "Im not sure what could be done here that would break less sites, but still  maintain the security guarantees of the extension.  I'm working on it! :)

 locked-down sites from getting access to blocked functionality, but injecting an iframe element into the page, and then pulling references to the blocked functionality out of the iframe (before the browser extension is able to modify the environment of the iframe)
