### ISSUE TITLE
"Unable to find the Web API Manager settings for [any site]"

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#25]
Is there a setting which causes this error msg?

**Comment by jawz101** [comment]
```

          "Unable to find the Web API Manager settings for https://github.com/snyderp/web-api-manager/issues/25"  instrument.js:45:9
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'sha256-TDpEIf38AE9ivvhMRfLLQ1Txa/xSgEPMlB/ljwlTSmI=' https://assets-cdn.github.com”). Source: (function (ERROR) {

    const V8_STACK_....  25:1
Empty string passed to getElementById().
```

**Comment by jawz101** [comment]
looks like maybe setting about:config preference privacy.firstparty.isolate = true causes the add-on not to function

**Comment by snyderp** [comment]
Great!  That'd be great to add to the wiki, thank you!

BTW, just curious how your version of FF got that flipped on?   Are you running TBB on a now default setting, or just running a very different config?

Just trying to get a sense of how common an issue this might be

**Comment by snyderp** [comment]
https://github.com/snyderp/web-api-manager/wiki/Known-Issues

**Comment by jawz101** [comment]
I flipped it myself.  Apparently it's part of the TOR browser bringup project or something.  Along with the pref privacy.resist.fingerprinting pref.

I just read about it on reddit a while ago and today I had toggled it but didn't realize that it was causing this add-on failing to log to console.

**Comment by jawz101** [comment]
... ergo I'm kinda doubting it will become a default for Firefox but probably for the TOR browser.  TOR and Mozilla started cooperating a while ago to incorporate TOR fingerprint protections into Firefox main as hidden preferences so there'd be less maintenance for TOR.

**Comment by Thorin-Oakenpants** [comment]
FPI (privacy.firstparty.isolate) and RFP (privacy.resistFingerprinting) are highly likely to become normal features in PB mode (private browsing). FPI is pretty much done (some sites & logins will always fail due to their login methods effectively using supercookie flows which FPI can't work around) and RFP is aiming at a UI preference in 59, once a few more teething problems are resolved and it is more front facing for the public

The problem with OA (origin attributes: FPI, PB, Containers - and these can be concatenated) is permissions. i.e: FPI and PB mode OAs are protected - not even extensions can handle them right now (eg cookie extensions and FPI = total failure) but this is being addressed, albeit slowly - see ticket [1381197](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197)

**Comment by snyderp** [comment]
Hmm, this will be a pickle if / when it becomes standard equipment.  I guess the thing to do if / when that happens will be to stay with the current cookie approach on Chrome, and then moving to (webRequest.filterResponseData)[https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/filterResponseData] for Firefox, to synchronously inject the settings into pages at `document_start`.  

Would be nice to not have to split the code base, but unless Firefox decides to not make this change, or Chrome adds `webRequest.filterResponseData`, guess there isn't much of a choice…

@Thorin-Oakenpants Any idea / word on what the timeline might be on this?

**Comment by Thorin-Oakenpants** [comment]
I am not sure why this would make any impact. FPI when on currently covers all windows. There is a proposal to change it from boolean to integer (on global, off global, on pb mode). Same for RFP, but that doesn't matter here. By making these changes, the idea is that PB mode could then take them up as standard settings.

However, the ticket to allow permissions on FPI and/or PB mode cookies will resolve your problem, not make it worse. In fact it opens up PB mode cookies more which wasn't available before. I could guess maybe by 59 since that is the next ESR, but I have a sneaky suspicion that TBB do not care about cookies anymore since they will be isolated and TBB uses PB mode anyway - so no change = status quo. Optimistically, I do not see this being resolved for ages (4 or 6 months?) but you never know what will happen now 57 has almost landed

**Comment by snyderp** [comment]
Ah, I see, this is extremely helpful.  Thanks for the rundown / details @Thorin-Oakenpants !  I'll take a deep breath for now :)

**Comment by jawz101** [comment]
er... https://www.reddit.com/r/technology/comments/79kzq4/firefox_58_will_become_the_first_of_the_major/

**Comment by snyderp** [comment]
Thats fantastic!  Anything that pushes the browser vendors to speed-bump pages' access to this kind of functionality is terrific :)
