### ISSUE TITLE
Does Firefox support File API?

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#34]
I was looking around and what I've read is Firefox does not support the [File API](https://www.w3.org/TR/file-system-api/) but made their own API called [DeviceStorageAPI ](https://wiki.mozilla.org/WebAPI/DeviceStorageAPI)controlled by about:config pref device.storage.enabled (defaulted to false).

Blog post from 2012 https://hacks.mozilla.org/2012/07/why-no-filesystem-api-in-firefox/

Now, this add-on does cause problems with YouTube if the File API is blocked, so it must be blocking something in Firefox that does indeed follow the File API, though I don't know what the device.storage.enabled pref for their homegrown API does.

**Comment by snyderp** [comment]
According to [CanIUse](https://caniuse.com/) its been in Firefox for a while (since v28 at least).

And its definitely in current versions too.  You can confirm this by opening up the console / developer tools and typing the follwing: `Blob.prototype.slice`.  You'll see it points to the function defined in the standard. 

Hope that helps!
