### ISSUE TITLE
I think Navigator.prototype.getBattery should just be Navigator.getBattery

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#51]
I think Navigator.prototype.getBattery should just be Navigator.getBattery

https://www2.w3c-test.org/battery-status
https://www.w3.org/TR/battery-status/

**Comment by snyderp** [comment]
I don't think this is is correct.  You can check this by doing `Navigator.prototype.getBattery` in Chrome, and you'll see that its a function, while `Navigator.getBattery` is undefined.

The confusion here might be that the location for this in the DOM is at `navigator.getBattery`, but thats because the global `navigator` object inherits from `Navigator`.  So `navigator.getBattery === Navigator.prototype.getBattery`.

Hope that helps explain :)
