### ISSUE TITLE
Just cosmetics: "DOM Level 4" in settings =" W3C DOM4" in console log

### ISSUE THREAD

**Issue by crssi** [snyderp/web-api-manager#54]
On the setting page we have `DOM Level 4`, but in the console log this is `W3C DOM4`

Cheers

**Comment by snyderp** [comment]
Thanks for the heads up :)

I'm going to close this for the moment, because I'm moving things over to a new logging interface with a new release I'll get out today or tomorrow, which will make bugs with current `console.log` interface irrelevant (though maybe at the cost of introducing many new bugs… :P)
