### ISSUE TITLE
General breakage on specific site

### ISSUE THREAD

**Issue by crssi** [snyderp/web-api-manager#55]
Firefox 57 on Windows
Fresh clean profile with only WAM installed, all FF settings at default.

If any blocking rule (just only one is enough) is checked, then this page [https://groups.google.com/forum/#!forum/ddawson-addonssupport](https://groups.google.com/forum/#!forum/ddawson-addonssupport) is blank.

If all blocking rules are cleared (is WAM disabled or not installed), then it loads just fine.

Cheers

**Comment by snyderp** [comment]
@crssi The issue here is my fix for #20, which makes direct cross frame communication impossible, which is needed to actually block pages from getting to the blocked DOM methods across frames.  

I've opened issues with FF and Chrome that would partially solve this problem, but in the meantime, i think this kind of breakage is a unavoidable side effect of the guarantees WAM wants to provide, given the current ways pages have access to DOMs across frames.

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1424176
Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=793217

Thank you for raising the issue though.  I'm going to close the issue now, but would be *very* grateful for any ideas folks have for improving things :)

**Comment by crssi** [comment]
Is it possible to implement when a domain is defined without any blocking rules, that WAM would net interfere at all.
It is not a good, but at least it is a solution to temporarily workaround a few pages to make them work until this is sorted out on higher level.
Same goes for #27 

Cheers

**Comment by crssi** [comment]
Same a written in the first post applies to [https://mail.google.com](https://mail.google.com).
After login, the page is loading indefinitely.

Cheers
