### ISSUE TITLE
tests and additional resources

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#56]
@snyderp do any of these resources look useful?
https://tests.caniuse.com
http://apimirror.com/dom/
http://apimirror.com
https://developer.mozilla.org/en-US/docs/MDN/Doc_status/API
https://github.com/mdn/kumascript/blob/master/macros/GroupData.json
https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/KumaScript

**Comment by snyderp** [comment]
@jawz101 yea, these look neat!  Thanks a gazillion for finding these!

Maybe it'd be worth moving these resources from the issue queue to a WIKI page, so they don't get lost when I close the issue?

Thoughts on each inline below:

https://tests.caniuse.com
---
This might be useful for determining if something is being blocked (though depends on how they do their testing).  WAM doesn't delete interfaces from the system, since that'd break a whole bunch of things w/ no compensating benefit.  Instead, the extension just tries to make those interfaces unable to modify the page.

http://apimirror.com/dom/
http://apimirror.com
---
This seems like the most valuable one of the group.  While I don't think it can replace looking at the standards documents directly and seeing whats defined in the WebIDL there, it could be very useful for finding out about new standards as they come out!

https://developer.mozilla.org/en-US/docs/MDN/Doc_status/API
---
Similar to the above, I don't think this could replace looking at each standards' WebIDL definitions, but could be a useful signal for when there are new standards to look at.

https://github.com/mdn/kumascript/blob/master/macros/GroupData.json
---
I'm not sure this one will be useful, since there isn't a mapping of methods exposed by each interface, which is whats needed from the WebIDL files.

https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/KumaScript
---
I'm not sure I understand the connection on this one though :)

**Comment by jawz101** [comment]
Thanks.  Yeah... I guess I could throw some out there on the Wiki but I didn't know which were relevant or helpful.  I was just googling around for certain things to find some tests and stuff

for instance, [this site](http://rednuht.org/genetic_cars_2/) seems to trigger a bunch of things and I was like "what is going on here?" Started looking at the code, had a few random thoughts and then I went down a rabbit hole.  It also made me wonder if our blocking this stuff would affect some sort of random number generators?  The reason I ask is because this particular site is a whole evolution simulator that tries to build the best car design.  I couldn't tell if the reason it triggered so many WebAPI alerts was because it uses characteristics of your browser, battery status, etc. as a way to introduce randomness to its mutation logic.  If, say, Web Cryptography relies on other variables from your system from which to draw its randomness, would we be effectively killing that randomness?

If I do add some to a resources wiki of sorts, maybe you can scrub out the useless ones.  I'm also looking at some of Chromium's source code to see how they validate their browser stuff as it references the same sorts of stuff in some code testing.  I mean, if anyone else has collected similar notes- might as well leverage it.

**Comment by snyderp** [comment]
Regarding random values / Web Crypto, I appreciate the concern, but I'm 100% certain the Web Crypto standard does not use other DOM methods to generate random values.  Web Crypto just calls into the OS's system for generating random info (e.x. in firefox: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/places/Helpers.cpp#214)

Its possible that some sites might try to roll their own random number generating solutions but grabbing other browser features, but that is is on them / their problem / not a good idea!  The entropy from the non cryptographic parts of the WebAPI is not going to be high enough to give you something that is 100% predictable.

Sure, if you create a wiki page I'd be happy to look at it.  And I think it can be helpful to look into the browser's testing systems, I'm skeptical it'll come to too much we can use easily, since they're testing very different situations (they want to make sure they implement standards, we want to know if websites break after a standard is removed).  But I could be wrong and I'm grateful for anything you find!
