### ISSUE TITLE
Stop using long strings as ids for standards

### ISSUE THREAD

**Issue by snyderp** [snyderp/web-api-manager#59]
This is a mistake i made from the getgo, where i wasn't thinking ahead and realizing that the system needs a fixed identifier for standards, distinct from a human readable (and changeable) name for each standard.

This issue tracks:

1. Create a numeric id for each standard
2. Write a migration routine to update any saved rules to use the new numeric id
3. Release that update
4. 1-2 weeks later, release an update that deletes the migration routines and any reference to the legacy string ids

**Comment by Thorin-Oakenpants** [comment]
> 4. 1-2 weeks later, release an update that deletes the migration routines and any reference to the legacy string ids

I'd wait longer. Example `Speed Dial [FVD]` released a web-ext hybrid. A number of things happened. They did it only 3 weeks out from 57. It was a complete disaster. They removed it. They then had another attempt, still a disaster, several more updates followed. People disabled automatic update extensions and rolled back to the legacy version. A pure web-ext was then released and 57 landed. People upgraded to FF57, found they needed to update the extension, did so, automagically got the latest pure web-ext version, missed the web-ext-hybrid version and lost all migration of data (although if you know what you are doing you can get it back). Woe and misery followed for tens of thousands of users.

So I would implement step 4 months down the track, or I guess you can code to only remove the migration routines if the update has been done - right? And the migration routine will check until it's been done, even in subsequent releases (eg what happens if a user missed the version that does the migration)?

Clearly I am not a coder :) But I think you get my drift. Any reason the migration check and cleanup can't be a single "step" and left in for the next 5 versions

**Comment by snyderp** [comment]
@Thorin-Oakenpants that makes sense to me.  I guess no reason to take the migration routines out except for some OCD on my part.  I take your point, best to leave them in place for a while.  Thanks for the nudge :)

**Comment by Thorin-Oakenpants** [comment]
OCD? .. lol .. if you think you're bad, I'm such a tidy freak it scares peoples... must find my meds... and I tend to ramble; I could have said all that above in about two lines now that I think of it :grin:
