### ISSUE TITLE
[feature request]  add NavigatorLanguage.language API

### ISSUE THREAD

**Issue by n8v8R** [snyderp/web-api-manager#69]
Whilst modifying the browser's response headers to obfuscate the user's language preferences this [API](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language) is rendering the header obsolete. Hence would appreciate it to be included in WAM.
> The NavigatorLanguage.language read-only property returns a string representing the preferred language of the user, usually the language of the browser UI
Returns the browser UI language, not the value of the Accept-Language HTTP header.

**Comment by snyderp** [comment]
Hmm, this will end up hanging on #67 (or maybe #42).  If I can get property blocking working in a consistent manner, then this would happen automatically when blocking the HTML5.1 standard (or, in the #42 approach, adding that feature to be blocked).  I'm working on it in the [67-block-properties](https://github.com/snyderp/web-api-manager/tree/67-block-properties) branch now. :)

**Comment by n8v8R** [comment]
If possible I would prefer it being separate from HTML5.1 as it might necessary but would want to escape Language fingerprinting through this API instead. Anyways thanks for your hard/excellent work!

**Comment by snyderp** [comment]
Gotcha gothca, makes sense.  The #42 case would I think realistically be the only way I'd get that into the extension then, since I don't want to go down the road of making more sub-sets of standards.  On the upside though, I think #42 would not be too bad to implement (fingers crossed).  I'll keep my progress on the issue posted at #42.  Thanks again!
