### ISSUE TITLE
[ISSUES] v0.9.22 - Cropped UI, No Del button (Opera Dev)

### ISSUE THREAD

**Issue by iWARR** [snyderp/web-api-manager#74]
1) UI is cropped in "granted" mode:

![webapi manager - crop ui issue](https://user-images.githubusercontent.com/33152262/36056802-7b43a568-0dff-11e8-860a-63d9d6ebdca6.png)

And I think, this window better make smaller (fonts, buttons and overall size).
There is no need to keep this clear and simple inteface with very few options so huge.

For example, regardless of uBlock Origin have almost same window size, it have much more options in the layout, more accurate (smaller) fonts and buttons in case of wide number of features in one place.

2) I don't see Delete `[X]` buttons anymore to manage domain names in the Permitting and Blocking lists. So, I can't delete them, if I want.

-------------

After next fixed build I'll test #73 fix and previous issues in Vivaldi (I have it installed also).
Thanks.

**Comment by snyderp** [comment]
@iWARR Thanks a  gazillion for filing these  issues!  On #73, I expect you'll still be seeing these issues b/c  I think the issue is that they haven't pull from the Chromium implementation of the WebExtensions implementation, and so their implementation doesn't follow the spec that current Chrome and FF do.

But for the other issues mentioned here, i expect they should be resolved by the new version.  If not though, please let me know.  I'd appreciate it a ton :)

**Comment by iWARR** [comment]
1) UI issues were fixed. Thanks!

2) The extension still have #68 issue on Vivaldi, but I'm sure you'll fix it together with Vivaldi communtiy.
