### ISSUE TITLE
unable to view this link nor troubleshoot breakage if anything is blocked while loading this url

### ISSUE THREAD

**Issue by jawz101** [snyderp/web-api-manager#79]
Surely it has something to do with the syntax used in this long ass url I made using Gerrit's search syntax.

https://review.lineageos.org/#/q/status:merged+branch:cm-14.1+AND+-translation+AND+-age:7days+AND+(project:%255E.*android_bootable_recovery+OR+project:%255E.*android_external_.*+OR+project:%255E.*android_frameworks_.*+OR+project:%255E.*android_hardware_qcom_.*+OR+project:%255E.*android_packages_.*+OR+project:%255E.*android_system_.*+OR+project:%255E.*android_vendor_.*+OR+project:%255E.*android+OR+project:%255E.*android_build+OR+project:%255E.*android_device_zte_axon7+OR+project:%255E.*android_kernel_zte_msm8996+OR+project:%255E.*cm_platform_sdk+OR+project:%255E.*lineageos_updater)

**Comment by snyderp** [comment]
@jawz101 This issue is b/c Gerrit's interface relies in on creating and reading content from `iframe`s, in a way that the extension can't guarantee is safe.  If you go into the advanced options in the extension, and uncheck the "Block cross-frame access" option, you'll see the page works correctly.

What I take from this issue though, is that it would be good to change the "Block cross-frame access" to be rule specific, instead of global.  That way, you could (for example) trust `review.lineagesos.org` to create and read from `iframe`s, and not everyone else.

I'm going to close this issue now, but if you disagree with any of above, please feel free to re-open it, or otherwise follow up!
